python3 run_language_modeling.py \
    --output_dir ./models/EsperBERTo-small-v1 \
    --model_type roberta \
    --mlm \
    --config_name ./models/EsperBERTo-small \
    --tokenizer_name ./models/EsperBERTo-small \
    --do_train \
    --do_eval \
    --learning_rate 1e-4 \
    --num_train_epochs 5 \
    --save_total_limit 2 \
    --save_steps 2000 \
    --per_gpu_train_batch_size 16 \
    --seed 42
